# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'RAEVO CRM'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/raevo-logo-thumbnail.svg'
- name: LOGO
  value: '/brand-assets/raevo-logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/raevo-logo.svg'
- name: BRAND_URL
  value: 'https://crm.raevo.io'
- name: WIDGET_BRAND_URL
  value: 'https://crm.raevo.io'
- name: BRAND_NAME
  value: 'RAEVO CRM'
- name: TERMS_URL
  value: 'https://www.chatwoot.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.chatwoot.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
- name: DISPLAY_UPDATE_BANNER
  value: false
  locked: false
  type: boolean
# ------- End of Branding Related Config ------- #
