json.id label.id
json.title label.title
json.description label.description
json.color label.color
json.show_on_sidebar label.show_on_sidebar
json.position label.position
json.visibility label.visibility
json.team_id label.team_id
json.created_by_id label.created_by_id
