json.id kanban_stage.id
json.account_id kanban_stage.account_id
json.kanban_board_id kanban_stage.kanban_board_id
json.name kanban_stage.name
json.color kanban_stage.color
json.icon kanban_stage.icon
json.description kanban_stage.description
json.category kanban_stage.category
json.wip_limit kanban_stage.wip_limit
json.probability kanban_stage.probability
json.position kanban_stage.position
json.active kanban_stage.active
json.created_at kanban_stage.created_at.to_i
json.updated_at kanban_stage.updated_at.to_i
