json.id kanban_stage.id
json.account_id kanban_stage.account_id
json.kanban_board_id kanban_stage.kanban_board_id
json.name kanban_stage.name
json.color kanban_stage.color
json.position kanban_stage.position
json.active kanban_stage.active
json.created_at kanban_stage.created_at.to_i
json.updated_at kanban_stage.updated_at.to_i
